language: python
python:
- "3.6"
before_install:
- git config --global push.default matching
- git config --global user.name "qiwihui via Travis CI"
- git config --global user.email "qwh005007@gmail.com"
install:
- pip install sphinx==1.5.6 sphinx-autobuild==0.7.1 sphinx-rtd-theme==0.4.1 
script:
- make html
- touch build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: build/html/
notifications:
  email:
    recipients:
    - qwh005007@gmail.com
    on_success: change
    on_failure: always
